package Tugas;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.*;

public class matkul extends javax.swing.JFrame {
    DefaultTableModel tabModel;
    ResultSet RsMatkul=null;
    /**
     * Creates new form matkul
     */
    public matkul() {
        initComponents();
        
        Dimension screenSize=Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize=this.getSize();
        if(frameSize.height > screenSize.height){
        frameSize.height=screenSize.height;
        }
        if(frameSize.width > screenSize.width){
        frameSize.width=screenSize.width;
        }
        this.setLocation((screenSize.width - frameSize.width) / 2,
        (screenSize.height = screenSize.height) / 20); 
        
        //fungsi Tampil data dan set edit off dijalankan saat aplikasi di run
        tampilData();
        SetEditOff();
    }
    
    //fungsi untuk menampilkan data matkul ke dalam tabel
    private void tampilData(){
        try{
            Object[] judul_kolom = {"Kode Mata Kuliah", "Nama Mata Kuliah", "Jumlah SKS", "Deadline", "Kelas"};
            tabModel=new DefaultTableModel(null,judul_kolom);
            TabelMatkul.setModel(tabModel);
            
            Connection conn=(Connection)koneksi.koneksiDB();
            Statement stt=conn.createStatement();
            tabModel.getDataVector().removeAllElements();
            
            RsMatkul=stt.executeQuery("SELECT * from matkul ");  
            while(RsMatkul.next()){
                Object[] data={
                    RsMatkul.getString("IDMatkul"),
                    RsMatkul.getString("NamaMatkul"),
                    RsMatkul.getString("SKS"),
                    RsMatkul.getString("Deadline"),
                    RsMatkul.getString("Kelas"),        
                };
               tabModel.addRow(data);
            }                
        } catch (Exception ex) {
        System.err.println(ex.getMessage());
        }
        // disable button
        jButtonSave.setEnabled(false);
        jButtonUpdate.setEnabled(false);
        jButtonDelete.setEnabled(false);
        jButtonCancel.setEnabled(false);
    }
   
    //menampilkan data ke form saat data pada tabel di klik 
   void tblKeForm(){
        jTextIDMatkul.setText(tabModel.getValueAt(TabelMatkul.getSelectedRow(),0)+"");
        jTextNama.setText(tabModel.getValueAt(TabelMatkul.getSelectedRow(),1)+"");
        jComboBoxSks.setSelectedItem(tabModel.getValueAt(TabelMatkul.getSelectedRow(),2)+"");
        jTextDeadline.setText(tabModel.getValueAt(TabelMatkul.getSelectedRow(),3)+"");
        jTextKelas.setText(tabModel.getValueAt(TabelMatkul.getSelectedRow(),4)+"");
        
        jButtonUpdate.setEnabled(true);
        jButtonDelete.setEnabled(true);
        jButtonCancel.setEnabled(true);
        jButtonSave.setEnabled(false);
    }
   
   //membersihkan form
   private void BersihData(){
        jTextIDMatkul.setText("");
        jTextNama.setText("");
        jComboBoxSks.setSelectedIndex(0);
        jTextDeadline.setText(""); 
        jTextKelas.setText("");
    } 
   
   //disable form
   private void SetEditOff(){
        jTextIDMatkul.setEnabled(false);
        jTextNama.setEnabled(false);
        jComboBoxSks.setEnabled(false);
        jTextDeadline.setEnabled(false);
        jTextKelas.setEnabled(false);
   }
   
   
   private void seteditOn(){
        jTextIDMatkul.setEnabled(true);
        jTextNama.setEnabled(true);
        jComboBoxSks.setEnabled(true);
        jTextDeadline.setEnabled(true);
        jTextKelas.setEnabled(true);
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelKodeProduk = new javax.swing.JLabel();
        jTextIDMatkul = new javax.swing.JTextField();
        jLabelNama = new javax.swing.JLabel();
        jTextNama = new javax.swing.JTextField();
        jLabelSatuan = new javax.swing.JLabel();
        jComboBoxSks = new javax.swing.JComboBox();
        jLabelHarga = new javax.swing.JLabel();
        jTextDeadline = new javax.swing.JTextField();
        jLabelStok = new javax.swing.JLabel();
        jTextKelas = new javax.swing.JTextField();
        jButtonAdd = new javax.swing.JButton();
        jButtonSave = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelMatkul = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Pencatat Tugas dan Deadline");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabelKodeProduk.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabelKodeProduk.setText("Kode Mata Kuliah");

        jTextIDMatkul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextIDMatkulActionPerformed(evt);
            }
        });
        jTextIDMatkul.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTextIDMatkulPropertyChange(evt);
            }
        });

        jLabelNama.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabelNama.setText("Nama Mata Kuliah");

        jLabelSatuan.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabelSatuan.setText("Jumlah SKS");

        jComboBoxSks.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3" }));
        jComboBoxSks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSksActionPerformed(evt);
            }
        });

        jLabelHarga.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabelHarga.setText("Deadline");

        jLabelStok.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabelStok.setText("Kelas");

        jButtonAdd.setText("Tambah");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jButtonSave.setText("Simpan");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jButtonUpdate.setText("Update");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        jButtonDelete.setText("Hapus");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Batal");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        TabelMatkul.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TabelMatkul.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        TabelMatkul.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TabelMatkul.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        TabelMatkul.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TabelMatkul.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelMatkulMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelMatkul);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelSatuan)
                                    .addComponent(jLabelNama)
                                    .addComponent(jLabelHarga)
                                    .addComponent(jLabelKodeProduk)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabelStok)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextNama, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxSks, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextDeadline, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextIDMatkul)
                            .addComponent(jTextKelas, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonAdd)
                        .addGap(6, 6, 6)
                        .addComponent(jButtonSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCancel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextIDMatkul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelKodeProduk))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNama))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxSks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelSatuan))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextDeadline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelHarga))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelStok))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonSave)
                            .addComponent(jButtonUpdate)
                            .addComponent(jButtonDelete)
                            .addComponent(jButtonCancel)
                            .addComponent(jButtonAdd)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //menangani proses saat button add di klik
    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        // TODO add your handling code here:
        BersihData();
        jTextIDMatkul.requestFocus();
        jButtonSave.setEnabled(true);
        jButtonUpdate.setEnabled(false);
        jButtonDelete.setEnabled(false);
        jButtonCancel.setEnabled(true);
        jButtonAdd.setEnabled(false);
        seteditOn();
    }//GEN-LAST:event_jButtonAddActionPerformed

    //menangani proses saat button save di klik
    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        // TODO add your handling code here:
        String IDMatkul=jTextIDMatkul.getText();
        String NamaMatkul=jTextNama.getText();
        String Sks=jComboBoxSks.getSelectedItem().toString();
        String Deadline=jTextDeadline.getText();
        String Kelas=jTextKelas.getText();
        jButtonAdd.setEnabled(true);

        if (IDMatkul.isEmpty() ) {
            JOptionPane.showMessageDialog(null,"Kode Mata Kuliah tidak boleh kosong");
            jTextIDMatkul.requestFocus();
        }else if (NamaMatkul.isEmpty()) {
            JOptionPane.showMessageDialog(null,"Nama Mata Kuliah tidak boleh kosong");
            jTextNama.requestFocus();
        }else if (Sks.isEmpty()) {
            JOptionPane.showMessageDialog(null,"Jumlah SKS tidak boleh kosong");
            jComboBoxSks.requestFocus();
        }else if (Deadline.isEmpty()) {
            JOptionPane.showMessageDialog(null,"Deadline tidak boleh kosong");
            jTextDeadline.requestFocus();
        }else if (Kelas.isEmpty()) {
            JOptionPane.showMessageDialog(null,"Kelas tidak boleh kosong");
            jTextKelas.requestFocus();
        }else{
            try{
                Connection conn=(Connection)koneksi.koneksiDB();
                Statement stt=conn.createStatement();
                stt.executeUpdate("insert into matkul(IDMatkul,NamaMatkul,SKS,Deadline,Kelas)"+
                    "VALUES('"+IDMatkul+"','"+NamaMatkul+"','"+Sks+"','"+Deadline+"','"+Kelas+"')");
                BersihData();
                tampilData();
                SetEditOff();
                JOptionPane.showMessageDialog(this,"Data berhasil disimpan","Success",JOptionPane.INFORMATION_MESSAGE);
            } catch(SQLException e){
                JOptionPane.showMessageDialog(this,"Simpan data gagal\n"+e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_jButtonSaveActionPerformed

    //menangani proses saat button Update di klik
    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        // TODO add your handling code here:
        String IDMatkul=jTextIDMatkul.getText();
        String NamaMatkul=jTextNama.getText();
        String Sks=jComboBoxSks.getSelectedItem().toString();
        String Deadline=jTextDeadline.getText();
        String Kelas=jTextKelas.getText();

        if (IDMatkul.isEmpty() ) {
            JOptionPane.showMessageDialog(null,"Kode Mata Kuliah tidak boleh kosong");
            jTextIDMatkul.requestFocus();
        }else if (NamaMatkul.isEmpty()) {
            JOptionPane.showMessageDialog(null,"Nama Mata Kuliah tidak boleh kosong");
            jTextNama.requestFocus();
        }else if (Sks.isEmpty()) {
            JOptionPane.showMessageDialog(null,"Jumlah SKS tidak boleh kosong");
            jComboBoxSks.requestFocus();
        }else if (Deadline.isEmpty()) {
            JOptionPane.showMessageDialog(null,"Deadline tidak boleh kosong");
            jTextDeadline.requestFocus();
        }else if (Kelas.isEmpty()) {
            JOptionPane.showMessageDialog(null,"Kelas tidak boleh kosong");
            jTextKelas.requestFocus();
        }
        else{
            try{
                Connection conn=(Connection)koneksi.koneksiDB();
                Statement stt=conn.createStatement();
                stt.executeUpdate("UPDATE matkul SET NamaMatkul ='"+NamaMatkul+"', SKS ='"+Sks+"', Deadline ='"+Deadline
                        +"', Kelas ='"+Kelas+"' WHERE IDMatkul ='"+IDMatkul+"'");
                BersihData();
                tampilData();
                SetEditOff();
                JOptionPane.showMessageDialog(this,"Data berhasil diubah","Success",JOptionPane.INFORMATION_MESSAGE);
            } catch(SQLException e){
                JOptionPane.showMessageDialog(this,"Ubah data gagal\n"+e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_jButtonUpdateActionPerformed

    //menangani proses saat button delete di klik
    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // TODO add your handling code here:
        String IDMatkul=jTextIDMatkul.getText();
        jButtonAdd.setEnabled(true);

        if (IDMatkul.isEmpty() ) {
            JOptionPane.showMessageDialog(null,"Kode Mata Kuliah tidak boleh kosong");
            jTextIDMatkul.requestFocus();
        }else if(JOptionPane.showConfirmDialog(null,"Apakah anda yakin akan menghapus data ini?",
            "Informasi",JOptionPane.OK_CANCEL_OPTION,JOptionPane.INFORMATION_MESSAGE)==JOptionPane.OK_OPTION){
        try{
            Connection conn=(Connection)koneksi.koneksiDB();
            Statement stt=conn.createStatement();
            stt.executeUpdate("DELETE FROM matkul WHERE IDMatkul='"+IDMatkul+"'");
            BersihData();
            tampilData();
            SetEditOff();
            JOptionPane.showMessageDialog(this,"Data berhasil di hapus","Success",JOptionPane.INFORMATION_MESSAGE);
        } catch(SQLException e){
            JOptionPane.showMessageDialog(this,"Delete data gagal\n"+e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }
        }
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    //menangani proses saat button cancel di klik
    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        // TODO add your handling code here:
        BersihData();
        jButtonSave.setEnabled(false);
        jButtonUpdate.setEnabled(false);
        jButtonDelete.setEnabled(false);
        jButtonCancel.setEnabled(false);
        jButtonAdd.setEnabled(true);
        SetEditOff();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    //menangani proses saat tabel matkul di klik
    private void TabelMatkulMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelMatkulMouseClicked
        // TODO add your handling code here:
        seteditOn();
        tblKeForm();
    }//GEN-LAST:event_TabelMatkulMouseClicked

    private void jComboBoxSksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxSksActionPerformed

    private void jTextIDMatkulPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTextIDMatkulPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextIDMatkulPropertyChange

    private void jTextIDMatkulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextIDMatkulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextIDMatkulActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(matkul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(matkul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(matkul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(matkul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new matkul().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelMatkul;
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JComboBox jComboBoxSks;
    private javax.swing.JLabel jLabelHarga;
    private javax.swing.JLabel jLabelKodeProduk;
    private javax.swing.JLabel jLabelNama;
    private javax.swing.JLabel jLabelSatuan;
    private javax.swing.JLabel jLabelStok;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextDeadline;
    private javax.swing.JTextField jTextIDMatkul;
    private javax.swing.JTextField jTextKelas;
    private javax.swing.JTextField jTextNama;
    // End of variables declaration//GEN-END:variables
}
